name-template: 'NucML v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
tag-prefix: "v"
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'task'
change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES

autolabeler:
  - label: 'feat'
    title:
      - '/feat:/'
  - label: 'fix'
    title:
      - '/fix:/'
  - label: 'docs'
    title:
      - '/docs:/'
  - label: 'refactor'
    title:
      - '/refactor:/'
  - label: 'perf'
    title:
      - '/perf:/'
  - label: 'test'
    title:
      - '/test:/'
  - label: 'chore'
    title:
      - '/chore:/'
  - label: 'breaking'
    body:
      - 'breaking change'