ame_dir_path = r'C:/Users/Pedro/Desktop/ML_Nuclear_Data/AME/CSV_Files' 
evaluations_path = r'C:/Users/Pedro/Desktop/ML_Nuclear_Data/Evaluated_Data' 
ensdf_path = r'C:/Users/Pedro/Desktop/ML_Nuclear_Data/ENSDF' 
exfor_path = r'C:/Users/Pedro/Desktop/ML_Nuclear_Data/EXFOR/CSV_Files' 
bench_template_path = r'C:/Users/Pedro/Desktop/ML_Nuclear_Data/Benchmarks/templates' 
ace_path = r'C:\Users\Pedro\Desktop\ML_Nuclear_Data\ACE' 
