"""File automatically generated by nucml-configure. This file can be amended if needed."""
ame_dir_path = r'C:\Users\Pedro\Desktop\ML_Nuclear_Data\AME\CSV_Files'
evaluations_path = r'C:\Users\Pedro\Desktop\ML_Nuclear_Data\Evaluated_Data'
ensdf_path = r'C:\Users\Pedro\Desktop\ML_Nuclear_Data\ENSDF'
exfor_path = r'C:\Users\Pedro\Desktop\ML_Nuclear_Data\EXFOR\CSV_Files'
bench_template_path = r'C:\Users\Pedro\Desktop\ML_Nuclear_Data\Benchmarks\inputs\templates'
ace_path = r'C:\Users\Pedro\Desktop\ML_Nuclear_Data'
matlab_path = r'C:\Users\Pedro\Desktop\ML_Nuclear_Data'
