"""Module containing path variables pointing towards data location.

This file is usually automatically generated by the `configure.py` module.
"""
ame_dir_path = r'C:/Users/Pedro/Desktop/ML_Nuclear_Data/AME/CSV_Files'
evaluations_path = r'C:/Users/Pedro/Desktop/ML_Nuclear_Data/Evaluated_Data'
ensdf_path = r'C:/Users/Pedro/Desktop/ML_Nuclear_Data/ENSDF'
exfor_path = r'C:/Users/Pedro/Desktop/ML_Nuclear_Data/EXFOR/CSV_Files'
bench_template_path = r'C:/Users/Pedro/Desktop/ML_Nuclear_Data/Benchmarks/inputs/templates'
# ace_path = r'C:\Users\Pedro\Desktop\ML_Nuclear_Data\ACE'
ace_path = r'C:/Users/Pedro/Documents/Serpent/xsdata/endfb7/acedata'
matlab_path = r"/mnt/c/Program\ Files/MATLAB/R2019a/bin/matlab.exe"
